name: Build and deploy server

on:
  push:
    branches: ["main"]
    paths:
      - "server/**"
  workflow_dispatch:

env:
  CONTEXT: server/
  IMAGE_NAME: mojadem/scfvi-server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and deploy Docker image
        uses: ./.github/actions/build-and-deploy
        with:
          context: ${{ env.CONTEXT }}
          image_name: ${{ env.IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          coolify_webhook: ${{ secrets.COOLIFY_SERVER_WEBHOOK }}
          coolify_token: ${{ secrets.COOLIFY_TOKEN }}
